### PR TITLE
Undeprecate ConsolePrompt methods et al

### LINKED ISSUE #1141: Review ConsolePrompt's method visibilities
1. `ConsolePrompt` do not implement `AutoCloseable`
2. Create `open()` method that set terminal in raw mode (the last four statement of the constructor) 
3. enclose prompt methods
    1) `public Map<String, PromptResultItemIF> prompt(List<AttributedString> header, List<PromptableElementIF> promptableElementList)` and 
    2) `public Map<String, PromptResultItemIF> prompt(List<AttributedString> headerIn, Function<Map<String, PromptResultItemIF>, List<PromptableElementIF>> promptableElementLists)` 
    
code with "open() - close()" i.e.
```
    public Map<String, PromptResultItemIF> prompt(...) throws IOException {
        try {
            open();
            ....
            ....
            return resultMap;
        } finally {
            close();
        }
    }
```
4. remove  `@Deprecated` statements
5. review `ConsolePrompt`'s other methods visibilities
6. fix examples

### PR DESCRIPTION
**Pull request by quintesse**
Implemented:

- open()/close() methods for ConsolePrompt
- calling open()/close() in prompt() methods that return Maps
- removed `@Deprecated` annotations
- removed new and unused (non Map returning) `prompt()` method
- made new (non Map returning) prompt() method `protected`
- fixed examples
- made sure all ConsolePrompt fields are `protected`

Fixes #1141

### CODE REVIEW

**Comment by quintesse** [comment]
Hi @mattirn , created this PR as a possible way to implement your suggestions from #1141

File: console-ui/src/main/java/org/jline/consoleui/prompt/ConsolePrompt.java [hunk 1]
```diff
@@ -30,12 +31,12 @@
 /**
  * ConsolePrompt encapsulates the prompting of a list of input questions for the user.
  */
-public class ConsolePrompt implements AutoCloseable {
+public class ConsolePrompt implements Closeable {
```
Comment (mattirn) [inline console-ui/src/main/java/org/jline/consoleui/prompt/ConsolePrompt.java]: ConsolePrompt should not implement Closeable interface

File: console-ui/src/main/java/org/jline/consoleui/prompt/ConsolePrompt.java [hunk 2]
```diff
@@ -69,10 +71,15 @@ public ConsolePrompt(LineReader reader, Terminal terminal, UiConfig config) {
             }
             config.setReaderOptions(options);
         }
-        attributes = terminal.enterRawMode();
-        terminal.puts(InfoCmp.Capability.enter_ca_mode);
-        terminal.puts(InfoCmp.Capability.keypad_xmit);
-        terminal.writer().flush();
+    }
+
+    public void open() {
```
Comment (mattirn) [inline console-ui/src/main/java/org/jline/consoleui/prompt/ConsolePrompt.java]: visibility of open() and close() methods should be changed to private

**Review by mattirn — CHANGES_REQUESTED** [review]

**Review by mattirn — APPROVED** [review]

**Review by cstamas — APPROVED** [review]

**Comment by quintesse** [comment]
Any idea when we could get a release with this merged? 😅
