### PR TITLE
Use simplified keymap for dumb terminal

### LINKED ISSUE #864: vi-style paren blinking causes unwanted "echo" in emacs
When using `sbt` from emacs (through `sbt-mode`), the terminal is set not to echo. However, if the input line contains parenthesis, the line is partially repeated.

```
scala> "foo"
val res1: String = foo

scala> "foo)bar"
"foo)val res2: String = foo()
```

Note on the last line the additional `"foo)`, which is not expected.

The behavior is possibly caused by the vi-style paren blinking: https://github.com/jline/jline3/blob/master/reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L2167

The question is, why is this functionality enabled for dumb terminals in sbt? Is there something wrong in how sbt uses jline3 or is it a bug in jline3 proper? I am available to help with a bug fix as soon as I understand which module to change.

### PR DESCRIPTION
**Pull request by hvesalai**
Fixes #864

### CODE REVIEW

**Comment by hvesalai** [comment]
Side note: during fixing this I run into some other problems. Most notably current implementation inhibits CRs from dumb terminal which means if you run 

`env TERM=dumb ./build repl`

The carriage return key will not do anything. The only way to do `ACCEPT_LINE` is `CTRL-J` (i.e. LF)

**Comment by hvesalai** [comment]
Side note 2: the first test in `reader/src/test/java/org/jline/terminal/impl/AbstractWindowsTerminalTest.java` (`testBracketingPasteSmall()`) was failing already before I started making this change and I didn't fix it. 

It should be noted that it will not work on dumb terminals unless the respective bind is added to the dumb terminal bindings, i.e. `bind(dumb, BEGIN_PASTE, BRACKETED_PASTE_BEGIN);`

File: reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java [hunk 1]
```diff
@@ -6263,6 +6270,14 @@ public KeyMap<Binding> safe() {
         return safe;
     }
 
+    public KeyMap<Binding> dumb() {
+        KeyMap<Binding> dumb = new KeyMap<>();
+        bind(dumb, SELF_INSERT, range("^@-^?"));
+        bind(dumb, ACCEPT_LINE, "\r", "\n");
```
Comment (gnodet) [inline reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java:6272]: Would adding `"\r\n"` as an additional key binding help with the cr/lf issue on dumb terminals ?

File: reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java [hunk 2]
```diff
@@ -6007,8 +6009,13 @@ public Map<String, KeyMap<Binding>> defaultKeyMaps() {
             keyMap.setUnicode(new Reference(SELF_INSERT));
             keyMap.setAmbiguousTimeout(getLong(AMBIGUOUS_BINDING, DEFAULT_AMBIGUOUS_BINDING));
         }
-        // By default, link main to emacs
-        keyMaps.put(MAIN, keyMaps.get(EMACS));
+        // By default, link main to emacs unless the temrinal is dumb
+
+        if (!isTerminalDumb()) {
```
Comment (gnodet) [inline reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java]: Could we use a ternary operator for brievity ? 
`keyMaps.put(MAIN, keyMaps.get(isTerminalDumb() ? DUMB : EMACS));

**Review by gnodet — CHANGES_REQUESTED** [review]

File: reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java (hunk 1 above)
Comment (hvesalai) [reply reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java:6272]: That would not be deterministic then. How will the system know if to expect only `\r` or `\r\n`. Remember that there might be no immediate input after the `\r`. Consider the following interaction:

Time `n`: user inputs something that triggers `SELF_INSERT`s, such as `"Hello"`
Time `n+1`: user inputs `\r`. 
Time `n+m`: user inputs a new thing that trigger `SELF_INSERT`s, not being `\n`, for example, `"World"`

Surely we cannot wait for a period of unkown `m` to determine whether the `\r` at `n+1` should have triggered `ACCEPT_LINE`.

Comment (hvesalai) [reply reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java:6272]: Consider above with this user over a slow connection:

Time `n`: process is piped something that triggers `SELF_INSERT`s, such as `"Hello"`
Time `n+1`: process is piped `\r`
Time `n+m`: process is piped `\n`

Waiting for the `\n` here would be possible (using a short timeout > `m`), but that would mean that a dumb terminal would always wait after a `\r` to see if there is a `\n` following it. Sometimes it could be available, sometimes not. The bottom line is that it would in any case slow down the process.

**Comment by hvesalai** [comment]
@gnodet this PR is actually more important for me. I think it should be quite clean, so maybe you could merge this now and I can continue with the other PR as needed.

**Review by gnodet — APPROVED** [review]
Looks good

**Comment by gnodet** [comment]
@hvesalai Unit tests are failing...

**Comment by hvesalai** [comment]
@gnodet yes I know. See note here https://github.com/jline/jline3/pull/874#issuecomment-1768273652

**Comment by gnodet** [comment]
> @gnodet yes I know. See note here [#874 (comment)](https://github.com/jline/jline3/pull/874#issuecomment-1768273652)
> 
> I wanted to get your feedback on how to fix this.

Something like the following should work:
```
diff --git a/reader/src/test/java/org/jline/terminal/impl/AbstractWindowsTerminalTest.java b/reader/src/test/java/org/jline/terminal/impl/AbstractWindowsTerminalTest.java
index f3dee5e6..85c9f30a 100644
--- a/reader/src/test/java/org/jline/terminal/impl/AbstractWindowsTerminalTest.java
+++ b/reader/src/test/java/org/jline/terminal/impl/AbstractWindowsTerminalTest.java
@@ -87,7 +87,7 @@ public class AbstractWindowsTerminalTest {
                     null,
                     new AnsiWriter(new BufferedWriter(sw)),
                     "name",
-                    AbstractWindowsTerminal.TYPE_DUMB,
+                    "windows",
                     Charset.defaultCharset(),
                     false,
                     SignalHandler.SIG_DFL,
(END)
```

**Comment by hvesalai** [comment]
@gnodet that fixes it, thank you! Pushed the fix to this PR.
